// This file takes the bootstrapped coefficients generated by "Models_10082021"
// and the "poisssonbootstrap" code and calculates a grand beta estimate, 
// standard errors, and p-values. I guess calling it a formatting file is a 
// bit misleading.  :)

// Arguements
* 1) File path of coefficients
* 2) Prefix used to add to variable names i.e. differentiate from other models
*    typically is the fixed effect of the model.



cap program drop formatcoefs
program define formatcoefs

	import delimited "`1'", clear
	rename (v1 y1) (coef_labels v1)
	* Beta and SE
	egen coefs = rowmean(v1-v1002)
	egen se = rowsd(v1-v1002)
	* 95% CI and P Val
	reshape long v, i(coef_labels)
	bys coef_labels: egen p025 = pctile(v), p(2.5)
	bys coef_labels: egen p975 = pctile(v), p(97.5)
	reshape wide v, i(coef_labels) j(_j)
	* Format
	gen coef_transorm = exp(coefs)
	order coef_labels coefs se p025 p975
	foreach y of var v1-v1002 {
		gen `y'_transformed = exp(`y')
	}
	egen se_transform = rowsd(v1_transformed-v1002_transformed)

	gen coefs_stars =  "*" if (p025 < 0 & p975 <0) | (p025 >0 & p975 >0)

	keep coef_labels coef_transorm se_transform coefs_stars
	foreach y of var coef_transorm se_transform coefs_stars {
		rename (`y') (`2'_`y')
	}
	split coef_labels, parse(:)
	drop coef_labels coef_labels1
	rename coef_labels2 coef_labels
	
end
